### ISSUE TITLE
How to satisfy "Do not use BuildContexts across async gaps" in a stateful widget?

### ISSUE THREAD

**Issue by sgham** [gtgalone/confirm_dialog#1]
After upgrading flutter, I have warnings about "Do not use BuildContext across async gaps".

What is the best way to avoiding the warnig when I am using await confirm( context, ... )

**Comment by gtgalone** [comment]
Hello @sgham 

the best way is
```dart
if (!mounted) {
  return null;
}
```

and another way
```dart
confirm(context, ...).then((String? value) async {
  print(value);
})
```
