### ISSUE TITLE
Issue when closing in a multi-context 

### ISSUE THREAD

**Issue by millerf** [gtgalone/confirm_dialog#2]
There is a bug when the parent Widget has a popable context.

To reproduce use "confirm()" within an openBottomSheet. Clicking either buttons will close the underlying sheet and break the app.

The context being "poppep" [here](https://github.com/gtgalone/confirm_dialog/blob/ba08b14281ace32c314125db5a595713d3f4cfbe/lib/confirm_dialog.dart#L18) is the wrong one and should be the context passed in the builder.

Changing

```
builder: (_) => WillPopScope(
```

to 
```
builder: (BuildContext context) => WillPopScope(
```

will solve the issue.

**Comment by gtgalone** [comment]
Hello @millerf !

Sorry for late reply. I was busy.

I just release with your request.

Please update to 1.0.3.

Thanks!

**Comment by millerf** [comment]
Thanks!
